---
on:
  - push

jobs:
  terraform:
    name: terraform
    env:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_TOKEN: "simple"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: default
      max-parallel: 3
    # This is solved in Terraform now.
    # services:
    #   vault:
    #     image: hashicorp/vault
    #     env:
    #       VAULT_DEV_ROOT_TOKEN_ID: "simple"
    #     ports:
    #       - 8200:8200
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_PASSWORD: postgres
    #     ports:
    #       - 5432:5432
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: terraform init
        uses: robertdebock/terraform-action@1.1.2
        with:
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform validate
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: validate
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform plan
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: plan
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform apply
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: apply
          directory: ./examples/${{ matrix.config.name }}
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
      - name: terraform destroy
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: destroy
          directory: ./examples/${{ matrix.config.name }}
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
        # if: ${{ always() }}
        # If terraform apply did not fail.
        if: ${{ success() }}
      - name: check container logs
        run: |
          for container in $(docker ps -q) ; do
            docker logs $container
          done
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vault
          vault status
        if: ${{ failure() }}
